import { Anuncio, Patrocinador, Cupom } from '../types';

export const INITIAL_MOCK_PATROCINADORES: Patrocinador[] = [
  {
    id: 'pat-1',
    nome: 'TechStore Brasil',
    imagem: 'https://images.unsplash.com/photo-1526738549149-8e07eca6c147?auto=format&fit=crop&w=1000&q=80',
    icone: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=200&q=80',
    link: 'https://example.com/techstore',
    ativo: true,
    ordem: 1,
    cliques: 1420,
    created_at: new Date().toISOString()
  },
  {
    id: 'pat-2',
    nome: 'Casa & Conforto',
    imagem: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80',
    icone: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=200&q=80',
    link: 'https://example.com/casaconforto',
    ativo: true,
    ordem: 2,
    cliques: 980,
    created_at: new Date().toISOString()
  },
  {
    id: 'pat-3',
    nome: 'Beleza Renovada',
    imagem: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1000&q=80',
    icone: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=200&q=80',
    link: 'https://example.com/belezarenovada',
    ativo: true,
    ordem: 3,
    cliques: 650,
    created_at: new Date().toISOString()
  }
];

export const INITIAL_MOCK_ANUNCIOS: Anuncio[] = [
  {
    id: 'anu-1',
    titulo: 'Fone de Ouvido Bluetooth Noise Cancelling PRO-X',
    descricao: 'Cancelamento ativo de ruído de última geração, bateria para até 35 horas contínuas de reprodução, almofadas super macias e microfone HD com IA para chamadas cristalinas.',
    categoria: 'Tecnologia',
    preco: 'R$ 299,90',
    localizacao: 'Envio para todo Brasil',
    link: 'https://amazon.com.br/dp/example1?tag=ofertasdahora-20',
    selo: 'Mais vendido',
    cupom: 'FONE15OFF',
    imagens: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80'],
    ativo: true,
    destaque: true,
    cliques: 843,
    patrocinador_id: 'pat-1',
    created_at: new Date(Date.now() - 3600000 * 2).toISOString()
  },
  {
    id: 'anu-2',
    titulo: 'Fritadeira Elétrica Air Fryer Digital 5.5L Inox',
    descricao: 'Prepare refeições crocantes e saudáveis sem usar óleo. Painel touch com 8 funções pré-programadas e cesto antiaderente removível de fácil limpeza.',
    categoria: 'Casa',
    preco: 'R$ 389,00',
    localizacao: 'Entrega Expressa',
    link: 'https://magazineluiza.com.br/example2?tag=ofertasdahora',
    selo: 'Oferta',
    cupom: 'AIRFRY20',
    imagens: ['https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=800&q=80'],
    ativo: true,
    destaque: true,
    cliques: 612,
    patrocinador_id: 'pat-2',
    created_at: new Date(Date.now() - 3600000 * 5).toISOString()
  },
  {
    id: 'anu-3',
    titulo: 'Kit Sérum Facial Ácido Hialurônico + Vitamina C',
    descricao: 'Tratamento intensivo anti-idade para hidratação profunda, uniformização do tom da pele e firmeza radiante. Dermatologicamente testado.',
    categoria: 'Beleza',
    preco: 'R$ 89,90',
    localizacao: 'Frete Grátis acima de R$ 99',
    link: 'https://shopee.com.br/example3',
    selo: 'Promoção',
    cupom: 'BELEZA10',
    imagens: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80'],
    ativo: true,
    destaque: false,
    cliques: 429,
    patrocinador_id: 'pat-3',
    created_at: new Date(Date.now() - 3600000 * 12).toISOString()
  },
  {
    id: 'anu-4',
    titulo: 'Smartwatch Esportivo AMOLED com GPS Integrado',
    descricao: 'Monitoramento cardíaco 24h, medição de oxigênio no sangue, mais de 100 modos de treino esportivo e resistência à água 5 ATM.',
    categoria: 'Tecnologia',
    preco: 'R$ 249,00',
    localizacao: 'Envio Internacional Prioritário',
    link: 'https://aliexpress.com/item/example4',
    selo: 'Novo',
    cupom: 'SMART30',
    imagens: ['https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=800&q=80'],
    ativo: true,
    destaque: true,
    cliques: 1205,
    patrocinador_id: 'pat-1',
    created_at: new Date(Date.now() - 3600000 * 24).toISOString()
  },
  {
    id: 'anu-5',
    titulo: 'Livro "Hábitos Atômicos" - Edição Especial Capa Dura',
    descricao: 'O bestseller mundial de James Clear sobre como construir bons hábitos e eliminar maus comportamentos com pequenas mudanças diárias.',
    categoria: 'Livros',
    preco: 'R$ 44,90',
    localizacao: 'Amazon Prime Elegível',
    link: 'https://amazon.com.br/dp/example5',
    selo: 'Mais vendido',
    cupom: null,
    imagens: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80'],
    ativo: true,
    destaque: false,
    cliques: 310,
    patrocinador_id: null,
    created_at: new Date(Date.now() - 3600000 * 30).toISOString()
  },
  {
    id: 'anu-6',
    titulo: 'Kit de Ferramentas Manuais Profissionais 108 Peças',
    descricao: 'Maleta rígida organizadora reforçada contendo catracas, soquetes, alicates, chaves de fenda e brocas de aço cromo vanádio de alta durabilidade.',
    categoria: 'Ferramentas',
    preco: 'R$ 199,90',
    localizacao: 'Envio Imediato',
    link: 'https://mercadolivre.com.br/example6',
    selo: 'Oferta',
    cupom: 'TOOL10',
    imagens: ['https://images.unsplash.com/photo-1581147036324-c17ac41dfa6c?auto=format&fit=crop&w=800&q=80'],
    ativo: true,
    destaque: false,
    cliques: 275,
    patrocinador_id: null,
    created_at: new Date(Date.now() - 3600000 * 48).toISOString()
  },
  {
    id: 'anu-7',
    titulo: 'Jaqueta Corta-Vento Esportiva Impermeável Unisex',
    descricao: 'Leve, dobrável e resistente à chuva e vento. Ideal para corrida, ciclismo ou uso casual urbano no dia a dia.',
    categoria: 'Moda',
    preco: 'R$ 119,90',
    localizacao: 'Frete Fixo R$ 9,90',
    link: 'https://netshoes.com.br/example7',
    selo: 'Promoção',
    cupom: 'MODA20',
    imagens: ['https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=80'],
    ativo: true,
    destaque: false,
    cliques: 198,
    patrocinador_id: null,
    created_at: new Date(Date.now() - 3600000 * 50).toISOString()
  },
  {
    id: 'anu-8',
    titulo: 'Suplemento Whey Protein Isolado 1kg + Coqueteleira',
    descricao: '27g de proteína pura por dose, zero açúcar e baixo teor de carboidratos. Excelente dissolução com sabores deliciosos.',
    categoria: 'Saúde',
    preco: 'R$ 129,90',
    localizacao: 'Entrega no mesmo dia para SP',
    link: 'https://growthsupplements.com.br/example8',
    selo: 'Oferta',
    cupom: 'FITNESS',
    imagens: ['https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?auto=format&fit=crop&w=800&q=80'],
    ativo: true,
    destaque: true,
    cliques: 512,
    patrocinador_id: null,
    created_at: new Date(Date.now() - 3600000 * 60).toISOString()
  }
];

export const INITIAL_MOCK_CUPONS: Cupom[] = [
  {
    id: 'cup-1',
    patrocinador_id: 'pat-1',
    titulo: '15% de Desconto em Eletrônicos e Gadgets',
    descricao: 'Válido para compras acima de R$ 150 em todos os itens de informática e tecnologia.',
    codigo: 'TECH15OFF',
    desconto: '15% OFF',
    link: 'https://example.com/techstore/desconto',
    tipo: 'cupom',
    expira_em: new Date(Date.now() + 86400000 * 7).toISOString(),
    ativo: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'cup-2',
    patrocinador_id: 'pat-2',
    titulo: 'Frete Grátis em Toda a Linha de Cozinha',
    descricao: 'Aproveite envio sem custo para qualquer região do Brasil sem valor mínimo de pedido.',
    codigo: 'FRETEGRATIS',
    desconto: 'Frete Grátis',
    link: 'https://example.com/casaconforto/frete',
    tipo: 'promocao',
    expira_em: new Date(Date.now() + 86400000 * 3).toISOString(),
    ativo: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'cup-3',
    patrocinador_id: 'pat-3',
    titulo: 'R$ 30 OFF na Primeira Compra em Cosméticos',
    descricao: 'Desconto especial para novos clientes em dermocosméticos e perfumes importados.',
    codigo: 'PRIMEIRA30',
    desconto: 'R$ 30 OFF',
    link: 'https://example.com/belezarenovada/cupom',
    tipo: 'cupom',
    expira_em: new Date(Date.now() + 86400000 * 14).toISOString(),
    ativo: true,
    created_at: new Date().toISOString()
  }
];
